/*

    Action Types

*/

export const INVALID_INPUT = 'INVALID_INPUT';
export type  INVALID_INPUT = typeof INVALID_INPUT;
export const API_ERROR = 'API_ERROR';
export type  API_ERROR = typeof API_ERROR;


export const REQUEST_GET_MOVIE_POSTERS = 'REQUEST_GET_MOVIE_POSTERS';
export type  REQUEST_GET_MOVIE_POSTERS = typeof REQUEST_GET_MOVIE_POSTERS;
export const DATA_LOADED_MOVIE_POSTERS = 'DATA_LOADED_MOVIE_POSTERS';
export type  DATA_LOADED_MOVIE_POSTERS = typeof DATA_LOADED_MOVIE_POSTERS;


export const REQUEST_GET_MOVIE_POSTER = 'REQUEST_GET_MOVIE_POSTER';
export type  REQUEST_GET_MOVIE_POSTER = typeof REQUEST_GET_MOVIE_POSTER;
export const REQUEST_POST_MOVIE_POSTER = 'REQUEST_POST_MOVIE_POSTER';
export type  REQUEST_POST_MOVIE_POSTER = typeof REQUEST_POST_MOVIE_POSTER;
export const REQUEST_PUT_MOVIE_POSTER = 'REQUEST_PUT_MOVIE_POSTER';
export type  REQUEST_PUT_MOVIE_POSTER = typeof REQUEST_PUT_MOVIE_POSTER;
export const REQUEST_DELETE_MOVIE_POSTER = 'REQUEST_DELETE_MOVIE_POSTER';
export type  REQUEST_DELETE_MOVIE_POSTER = typeof REQUEST_DELETE_MOVIE_POSTER;
export const DATA_LOADED_MOVIE_POSTER = 'DATA_LOADED_MOVIE_POSTER';
export type  DATA_LOADED_MOVIE_POSTER = typeof DATA_LOADED_MOVIE_POSTER;


export const REQUEST_GET_MOVIES = 'REQUEST_GET_MOVIES';
export type  REQUEST_GET_MOVIES = typeof REQUEST_GET_MOVIES;
export const DATA_LOADED_MOVIES = 'DATA_LOADED_MOVIES';
export type  DATA_LOADED_MOVIES = typeof DATA_LOADED_MOVIES;

export const REQUEST_GET_MOVIE = 'REQUEST_GET_MOVIE';
export type  REQUEST_GET_MOVIE = typeof REQUEST_GET_MOVIE;
export const REQUEST_PUT_MOVIE = 'REQUEST_PUT_MOVIE';
export type  REQUEST_PUT_MOVIE = typeof REQUEST_PUT_MOVIE;
// export const ADDED_NEW_MOVIE = 'ADDED_NEW_MOVIE';
// export type  ADDED_NEW_MOVIE = typeof ADDED_NEW_MOVIE;
// export const DELETED_MOVIE = 'DELETED_MOVIE';
// export type  DELETED_MOVIE = typeof DELETED_MOVIE;
export const DATA_LOADED_MOVIE = 'DATA_LOADED_MOVIE';
export type  DATA_LOADED_MOVIE = typeof DATA_LOADED_MOVIE;


export const REQUEST_ADD_REVIEW = 'REQUEST_ADD_REVIEW';
export type  REQUEST_ADD_REVIEW = typeof REQUEST_ADD_REVIEW;
export const REQUEST_EDIT_REVIEW = 'REQUEST_EDIT_REVIEW';
export type  REQUEST_EDIT_REVIEW = typeof REQUEST_EDIT_REVIEW;
export const REQUEST_DELETE_REVIEW = 'REQUEST_DELETE_REVIEW';
export type  REQUEST_DELETE_REVIEW = typeof REQUEST_DELETE_REVIEW;
export const DATA_LOADED_REVIEW = 'DATA_LOADED_REVIEW';
export type  DATA_LOADED_REVIEW = typeof DATA_LOADED_REVIEW;

/*

    UI State

*/

export const THEME_DEFAULT = 'THEME_DEFAULT';
export type  THEME_DEFAULT = typeof THEME_DEFAULT;
export const THEME_HIGH_CONTRAST = 'THEME_HIGH_CONTRAST';
export type  THEME_HIGH_CONTRAST = typeof THEME_HIGH_CONTRAST;
export type THEME_SETTING = THEME_DEFAULT | THEME_HIGH_CONTRAST;

export const SR_OFF = 'SR_OFF';
export type  SR_OFF = typeof SR_OFF;
export const SR_ON = 'SR_ON';
export type  SR_ON = typeof SR_ON;
// export const SR_BROWSE_MODE = 'SR_BROWSE_MODE';
// export type  SR_BROWSE_MODE = typeof SR_BROWSE_MODE;
// export const SR_FORM_MODE = 'SR_FORM_MODE';
// export type  SR_FORM_MODE = typeof SR_FORM_MODE;
export type SR_SETTING = SR_OFF | SR_ON;

export const ANIMATIONS_ON = 'ANIMATIONS_ON';
export type  ANIMATIONS_ON = typeof ANIMATIONS_ON;
export const ANIMATIONS_OFF = 'ANIMATIONS_OFF';
export type  ANIMATIONS_OFF = typeof ANIMATIONS_OFF;
export type ANIMATION_SETTING = ANIMATIONS_ON | ANIMATIONS_OFF;

export const UI_INIT = 'UI_INIT';
export type  UI_INIT = typeof UI_INIT;
export const UI_LOADING = 'UI_LOADING';
export type  UI_LOADING = typeof UI_LOADING;
export const UI_LOADED = 'UI_LOADED';
export type  UI_LOADED = typeof UI_LOADED;
export const UI_ERROR = 'UI_ERROR';
export type  UI_ERROR = typeof UI_ERROR;
export type UI_STATE = UI_INIT | UI_LOADING | UI_LOADED | UI_ERROR;